[versions]
# libraries
assertj = "3.27.6"
coroutines = "1.10.2"
junit = "6.0.1"
junitJupiter = "6.0.1"
junitPlatform = "6.0.1"
kodein = "7.30.0"
kotest = "6.0.7"
mockk = "1.14.7"
mockito = "5.20.0"
opentest4j = "1.3.0"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.3"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
junit-mockito = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junitPlatform" }
kotest-assertion = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kodein = { module = "org.kodein.di:kodein-di-jvm", version.ref = "kodein" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
mocking-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mocking-mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
